name: CSV Aktarma

on:
  workflow_dispatch:

jobs:
  create_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create CSV
        run: |
          ls ${{ github.action_path }}

  use_csv:
    runs-on: ubuntu-latest
    needs: create_csv
    steps:
      - name: Checkout repository
        run: ls ${{ github.action_path }}
