name: Install

on: workflow_dispatch

jobs:
  Kategori:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        K_LOC: ["links-0.txt", "links-1.txt", "links-2.txt","links-3.txt","links-4.txt"]
        mongodb-version: ["5.0"]
    steps:
        - name: checkout repo content
          uses: actions/checkout@v3 # checkout the repository content
    container:
      image: python:3.9
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
