name: Install

on: workflow_dispatch

jobs:
  Kategori:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        K_LOC: ["links-0.txt", "links-1.txt", "links-2.txt","links-3.txt","links-4.txt"]
        mongodb-version: ["5.0"]
    steps:
        - name: checkout repo content
          uses: actions/checkout@v3 # checkout the repository content

        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: "3.9" # install the python version needed

        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Dawnload Dataset # run main.py
          env:
            # Kaggle API auth
            KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
            KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
            DATASET_PATH: ${{ vars.BKM_KAGGLE_DATASET_PATH }}
          run: python Scripts/dataset_import.py

    container:
      image: python:3.9
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
  Deger:
    runs-on: ubuntu-latest
    needs: Kategori
    steps:
      - name: checkout repo content
        run: ls ${{ github.workspace }} # checkout the repository conten
      


      
