name: BKM Kitap Query-test

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 0 * * *" # Hergün saat 00:00 da

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        K_LOC: ["links-0.txt", "links-1.txt", "links-2.txt","links-3.txt","links-4.txt"]
        mongodb-version: ["5.0"]
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9" # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Dawnload Dataset # run main.py
        env:
          # Kaggle API auth
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: python Scripts/dataset_import.py
      
      - name: Kategori File Create # run main.py
        run: python Scripts/bkm_categori_list_create.py
      
      - name: Script Start # run main.py
        run: python Scripts/bkmkitap.com_scripts/bkm_new_data.py
        env:
          # Kaggle API auth
          K_LOC": ${{ matrix.K_LOC }}

      - name:
          Kaggle Sync
          # only sync when there is push to master
        env:
          # Kaggle API auth
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          cd Datasets
          kaggle datasets metadata ${{ vars.KAGGLE_DATASET_PATH}}
          python ../Scripts/kaggleUpload.py