name: Haftalık Rapor ve Dashboard Oluşturma

on:
  schedule:
    - cron: '0 10 * * 0'  # Her Pazar saat 10:00 UTC'de çalışacak
  workflow_dispatch:  # Manuel çalıştırma seçeneği

env:
  LOG_FILE: 'report.log'

jobs:
  generate-reports:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install plotly pandas kaggle

    - name: Create directories
      run: |
        mkdir -p Report Data logs
    
    - name: Download BKM Dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        python -m Scripts.dataset_download --dataset_name furkanzeki/bkm-book-dataset

    - name: Download KY Dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        python -m Scripts.dataset_download --dataset_name furkanzeki/kitap-yurdu-dataset

    - name: Generate Report and Dashboard
      run: |
        mkdir -p Report
        python -m Scripts.report
        echo "Rapor oluşturma işlemi tamamlandı: $(date)"

    - name: Check Report Generation 
      id: check_report
      run: |
        if [ -d "Report" ] && ls Report/*.html 1> /dev/null 2>&1; then
          echo "Report başarıyla oluşturuldu."
          echo "REPORT_GENERATED=true" >> $GITHUB_ENV
          echo "Generated reports:"
          ls -la Report/
        else
          echo "Report oluşturma hatası!"
          echo "REPORT_GENERATED=false" >> $GITHUB_ENV
          echo "Report directory contents:"
          ls -la Report/ || echo "Report directory does not exist"
          exit 1
        fi

    - name: Update index.html with new reports
      if: env.REPORT_GENERATED == 'true'
      run: |
        echo "Updating index.html with new reports..."
        # This step could be enhanced to automatically update the reports array in index.html
        # For now, we'll just ensure the reports are available

    - name: Commit and push reports
      if: env.REPORT_GENERATED == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config pull.rebase false
        git pull origin main
        # Check if there are report files to commit
        if [ -d "Report" ] && [ "$(ls -A Report/)" ]; then
          git add Report/*.html
          echo "Added report files"
        fi
        # Add index.html if it exists
        if [ -f "index.html" ]; then
          git add index.html
          echo "Added index.html"
        fi
        # Only commit if there are changes
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          TODAY=$(date +'%Y-%m-%d')
          git commit -m "Haftalık Rapor ve Dashboard eklendi - Modern UI güncellemesi - $TODAY"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
