name: Haftalık Rapor ve Dashboard Oluşturma

on:
  schedule:
    - cron: '0 10 * * 0'  # Her Pazar saat 10:00 UTC'de çalışacak
  workflow_dispatch:  # Manuel çalıştırma seçeneği

env:
  LOG_FILE: 'report.log'

jobs:
  generate-reports:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          Dataset: [bkm-book-dataset, kitap-yurdu-dataset]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install plotly pandas kaggle
    
    - name: Kaggle Dataset Download
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        python -m Scripts.dataset_download --dataset_name furkanzeki/${{matrix.Dataset}}

    - name: Generate Report and Dashboard
      run: |
        mkdir -p Report
        python -m Scripts.report
        echo "Rapor oluşturma işlemi tamamlandı: $(date)"

    - name: Check Report Generation 
      id: check_report
      run: |
        if [ -d "Report" ] && ls Report/*.html 1> /dev/null 2>&1; then
          echo "Report başarıyla oluşturuldu."
          echo "REPORT_GENERATED=true" >> $GITHUB_ENV
        else
          echo "Report oluşturma hatası!"
          echo "REPORT_GENERATED=false" >> $GITHUB_ENV
          exit 1
        fi

    - name: Commit and push reports
      if: env.REPORT_GENERATED == 'true'
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git pull origin main
        git add Report/*.html
        TODAY=$(date +'%Y-%m-%d')
        git commit -m "Haftalık Rapor ve Dashboard eklendi - ${{ matrix.Dataset }} - $TODAY"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
